name: Build caddy-custom

# Controls when the action will run
on:
  workflow_dispatch:  # allows to run the workflow manually from the Actions tab
  schedule:
    - cron: '0 0 1 * *'  # runs at 00:00 on the first day of every month
  push:
    branches: main


# Environment variables available to all jobs and steps in this workflow
env:
  version: 2.8.4
  labels: 2.8.4
  tags: 2.8.4,latest
  platforms: linux/amd64,linux/arm64
 
# Jobs to run once the workflow is triggered
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

          
 #   - name: Build the Docker image
 #     run: docker build . --file Dockerfile --tag caddy-custom:latest

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.7.0
      with:
        push: true
        tags: ${{ needs.metadata.outputs.tags }}
        labels: ${{ needs.metadata.outputs.labels }}
        platforms: ${{ needs.metadata.outputs.platforms }}
